### ISSUE TITLE
Issue with Halt drive or movement code

### ISSUE THREAD

**Issue by mdttrump97** [FTC3486/OpModes#3]
Sometimes the drive train doesn't stop before the climber dump dumps the climbers. It may be an issue in the encoderAutoDriver drive_backwards method or halt drive; I'm not sure.

**Comment by JacobAMason** [comment]
In which Autonomous OpModes have you seen this issue?

**Comment by mdttrump97** [comment]
Both blue and red automodes

**Comment by JacobAMason** [comment]
Red has a Park and a Smash?

**Comment by mdttrump97** [comment]
I didn't mean to commit that yet , but yes. Blue will have one too.

**Comment by JacobAMason** [comment]
So just in the Parks? Or have you verified it is in both Park and Smash?

**Comment by mdttrump97** [comment]
No, I haven't tested smash.

**Comment by JacobAMason** [comment]
Okay. We can take a look at it tomorrow. I just wanted to be up to speed on what happening so I could show up and we could fix stuff.

**Comment by mdttrump97** [comment]
Ok. Are you coming to the meeting?

**Comment by JacobAMason** [comment]
@mdttrump97 Is this still an issue?

**Comment by mdttrump97** [comment]
Yes, it popped up again last night; it almost seems like it's a thread issue.

**Comment by JacobAMason** [comment]
What do you mean? And are we good to merge the new branch to master / did any additional issues come up in testing?

**Comment by mdttrump97** [comment]
The only issue that we found was this one. The robot acts like the drive train gets frozen in time and continues the same movement (driving into a wall, turning awkwardly slowly, etc.) but the rest of the robot acts fine (dumps the climbers, etc.).

Basically, it acts like maybe the drivetrain runmodes are still messing up.

**Comment by JacobAMason** [comment]
Mkay. That's super odd and probably something weird we are doing, but I can't think of what it could be. I'll go ahead and push the merge into master.

**Comment by mdttrump97** [comment]
Is there a way to visual all of the underlying program threads to see what all it is doing? Maybe extended dcmotor isn't doing its job...

**Comment by JacobAMason** [comment]
![What do you mean?](https://cloud.githubusercontent.com/assets/7819697/14359610/e96464ac-fcb7-11e5-9661-5b2eb33b030e.png)
